[package]
name = "supervisor"
version = "0.1.0"
edition = "2021"

[dependencies]
intrusive-collections = { version = "0.9", default-features = false }
spin = "0.9"

multiboot = { path = "multiboot" }
